"""
Standard schema definitions, platform signal maps, and column synonym lookups.
All other modules import from here. No project imports.
"""

# ── Standard output columns (canonical order) ────────────────────────────────

STANDARD_COLUMNS = [
    "date",
    "platform",
    "campaign_name",
    "campaign_id",
    "ad_group_name",
    "ad_group_id",
    "ad_name",
    "ad_id",
    "impressions",
    "reach",
    "clicks",
    "spend",
    "conversions",
    "conversion_value",
    "ctr",               # always stored as decimal: 0.0125 not 1.25%
    "cpc",
    "cpm",
    "roas",
    "frequency",
    "video_views",
    "video_view_rate",
    "quality_score",
    "search_impression_share",
]

# Columns that should be stored as decimals (not percentages)
PERCENTAGE_COLUMNS = {"ctr", "video_view_rate", "search_impression_share"}

# Columns that are currency values
CURRENCY_COLUMNS = {"spend", "cpc", "cpm", "roas", "conversion_value"}

# ── Platform detection signals ────────────────────────────────────────────────
# Substrings (lowercase) in column headers that identify the platform.
# Each signal list is weighted — more specific signals score higher.

PLATFORM_SIGNALS = {
    "google_ads": [
        "quality score",
        "search impr. share",
        "avg. cpc",
        "campaign state",
        "ad group state",
        "final url",
        "match type",
        "search term",
        "keyword state",
        "bid strategy type",
        "top of page rate",
        "interaction rate",
    ],
    "meta": [
        "reach",
        "frequency",
        "result type",
        "cost per result",
        "amount spent",
        "post engagement",
        "thumbstop ratio",
        "hook rate",
        "3-second video views",
        "cost per 1,000 accounts reached",
        "outbound clicks",
    ],
    "ga4": [
        "session default channel group",
        "landing page",
        "bounce rate",
        "engaged sessions",
        "event count",
        "total revenue",
        "session medium",
        "session source",
        "new users",
        "engagement rate",
    ],
    "tiktok": [
        "video views",
        "average watch time",
        "profile visits",
        "follows",
        "cost per 1000 reached",
        "video play actions",
        "6-second video views",
        "anchor clicks",
        "interactive add-on",
    ],
    "linkedin": [
        "sponsored content",
        "document ads",
        "message ads",
        "total engagements",
        "viral impressions",
        "average engagement rate",
        "job title",
        "campaign group name",
        "seniority",
    ],
    "microsoft_ads": [
        "bing",
        "average position",
        "phone calls",
        "phone impressions",
        "bid match type",
        "delivered match type",
        "ad distribution",
    ],
    "pinterest": [
        "pin clicks",
        "closeups",
        "saves",
        "outbound clicks",
        "total audience",
        "paid impressions",
        "earned impressions",
    ],
}

# Minimum number of signals required to confirm a platform detection
PLATFORM_SIGNAL_THRESHOLD = 2

# ── Column synonym maps ───────────────────────────────────────────────────────
# Maps raw export column name (lowercase, stripped) → standard column name.
# None means the column should be dropped from the output.

COLUMN_SYNONYMS = {
    "google_ads": {
        "day": "date",
        "week": "date",
        "month": "date",
        "quarter": "date",
        "year": "date",
        "campaign": "campaign_name",
        "campaign id": "campaign_id",
        "ad group": "ad_group_name",
        "ad group id": "ad_group_id",
        "ad": "ad_name",
        "ad id": "ad_id",
        "impr.": "impressions",
        "impressions": "impressions",
        "clicks": "clicks",
        "interactions": "clicks",
        "cost": "spend",
        "cost (usd)": "spend",
        "avg. cpc": "cpc",
        "avg. cpm": "cpm",
        "ctr": "ctr",
        "interaction rate": "ctr",
        "conversions": "conversions",
        "conv.": "conversions",
        "conv. value": "conversion_value",
        "all conv. value": "conversion_value",
        "search impr. share": "search_impression_share",
        "quality score": "quality_score",
        "video views": "video_views",
        "view rate": "video_view_rate",
        # drop these
        "currency code": None,
        "campaign state": None,
        "ad group state": None,
        "final url": None,
        "match type": None,
        "bid strategy type": None,
    },
    "meta": {
        "day": "date",
        "week": "date",
        "month": "date",
        "reporting starts": "date",
        "date start": "date",
        "campaign name": "campaign_name",
        "campaign id": "campaign_id",
        "ad set name": "ad_group_name",
        "ad set id": "ad_group_id",
        "ad name": "ad_name",
        "ad id": "ad_id",
        "impressions": "impressions",
        "reach": "reach",
        "frequency": "frequency",
        "clicks (all)": "clicks",
        "link clicks": "clicks",
        "outbound clicks": "clicks",
        "amount spent (usd)": "spend",
        "amount spent": "spend",
        "cpm (cost per 1,000 impressions)": "cpm",
        "cpc (all)": "cpc",
        "cpc (cost per link click)": "cpc",
        "ctr (all)": "ctr",
        "ctr (link click-through rate)": "ctr",
        "purchases": "conversions",
        "results": "conversions",
        "purchase roas (return on ad spend)": "roas",
        "website purchase roas (return on ad spend)": "roas",
        "purchase conversion value": "conversion_value",
        "3-second video plays": "video_views",
        "video plays": "video_views",
        "video average play time": None,
        # drop these
        "reporting ends": None,
        "delivery": None,
        "objective": None,
        "buying type": None,
        "ad set budget": None,
        "ad set budget type": None,
    },
    "ga4": {
        "date": "date",
        "week": "date",
        "month": "date",
        "session campaign": "campaign_name",
        "session google ads campaign": "campaign_name",
        "session google ads ad group name": "ad_group_name",
        "sessions": "clicks",
        "users": None,
        "new users": None,
        "conversions": "conversions",
        "total revenue": "conversion_value",
        "session default channel group": None,
        "session source": None,
        "session medium": None,
        "landing page": None,
        "bounce rate": None,
        "engaged sessions": None,
        "engagement rate": None,
        "event count": None,
    },
    "tiktok": {
        "date": "date",
        "campaign name": "campaign_name",
        "campaign id": "campaign_id",
        "ad group name": "ad_group_name",
        "ad group id": "ad_group_id",
        "ad name": "ad_name",
        "ad id": "ad_id",
        "impressions": "impressions",
        "reach": "reach",
        "clicks (destination)": "clicks",
        "clicks": "clicks",
        "cost": "spend",
        "cpm": "cpm",
        "cpc": "cpc",
        "ctr": "ctr",
        "conversions": "conversions",
        "total complete payment": "conversions",
        "total complete payment rate": None,
        "video views": "video_views",
        "average watch time per video view": None,
        "video watched 2s": None,
        "video watched 6s": None,
        # drop these
        "campaign objective": None,
        "ad group status": None,
        "ad status": None,
        "split test": None,
    },
    "linkedin": {
        "start date (in utc)": "date",
        "end date (in utc)": None,
        "campaign group name": "campaign_name",
        "campaign group id": "campaign_id",
        "campaign name": "ad_group_name",
        "campaign id": "ad_group_id",
        "creative name": "ad_name",
        "creative id": "ad_id",
        "impressions": "impressions",
        "clicks": "clicks",
        "amount spent (usd)": "spend",
        "average cpm": "cpm",
        "average cpc": "cpc",
        "click through rate (ctr)": "ctr",
        "conversions": "conversions",
        "total engagements": None,
        "viral impressions": None,
        "viral clicks": None,
        # drop these
        "campaign status": None,
        "campaign type": None,
        "objective type": None,
    },
    "microsoft_ads": {
        "day": "date",
        "campaign": "campaign_name",
        "campaign id": "campaign_id",
        "ad group": "ad_group_name",
        "ad group id": "ad_group_id",
        "ad id": "ad_id",
        "impressions": "impressions",
        "clicks": "clicks",
        "spend": "spend",
        "avg. cpc": "cpc",
        "avg. cpm": "cpm",
        "ctr": "ctr",
        "conversions": "conversions",
        "revenue": "conversion_value",
        "quality score": "quality_score",
        # drop these
        "currency code": None,
        "bid match type": None,
        "delivered match type": None,
    },
    "pinterest": {
        "date": "date",
        "campaign name": "campaign_name",
        "campaign id": "campaign_id",
        "ad group name": "ad_group_name",
        "ad group id": "ad_group_id",
        "ad name": "ad_name",
        "ad id": "ad_id",
        "impressions": "impressions",
        "outbound clicks": "clicks",
        "spend (usd)": "spend",
        "ecpm": "cpm",
        "ecpc": "cpc",
        "ctr": "ctr",
        "conversions": "conversions",
        # drop these
        "pin clicks": None,
        "closeups": None,
        "saves": None,
        "campaign status": None,
    },
    # Runtime cache for Claude-resolved unknown columns
    "_generic": {},
}

# ── Footer / metadata row detection patterns ──────────────────────────────────

# Regex patterns matched against the first cell of a row (case-insensitive)
FOOTER_PATTERNS = [
    r"^total$",
    r"^grand total",
    r"^summary$",
    r"^subtotal",
    r"^report total",
    r"^all campaigns",
    r"^disclaimer",
    r"^data pulled",
    r"^exported",
    r"^generated (by|on)",
    r"^source:",
    r"^\s*$",
]

# Substrings (lowercase) commonly found in pre-header metadata rows
METADATA_PATTERNS = [
    "date range",
    "account name",
    "account id",
    "report name",
    "currency",
    "timezone",
    "filters applied",
    "segment",
    "downloaded",
    "created by",
    "report type",
    "google ads",
    "meta ads",
    "facebook ads",
    "tiktok ads manager",
    "linkedin campaign manager",
    "microsoft advertising",
    "pinterest ads",
    "billing",
    "advertiser",
    "reporting period",
]
